apiVersion: apps/v1
kind: Deployment
metadata:
  name: churchlify-webapp
  namespace: churchlify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churchlify-webapp
  template:
    metadata:
      labels:
        app: churchlify-webapp
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: worker

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: churchlify-webapp

      containers:
      - name: churchlify-webapp
        image: ghcr.io/churchlify/churchlify-web:latest
        ports:
        - containerPort: 3000

        # Load app-specific env vars
        envFrom:
        - secretRef:
            name: churchlify-secrets
        - secretRef:
            name: global-db-secrets

        env:
        - name: MONGO_URI
          value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@$(MONGO_HOST):$(MONGO_PORT)/$(APP_DB_NAME)?authSource=admin"

        volumeMounts:
        - name: files
          mountPath: /usr/src/app/files_upload

      volumes:
      - name: files
        persistentVolumeClaim:
          claimName: churchlify-webapp-files
