apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console-ingress
  namespace: platform
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod # If using SSL
spec:
  tls:
  - hosts:
    - minio.churchlify.com
    secretName: minio-tls
  rules:
  - host: minio.churchlify.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9001 # Console Port