apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api-ingress
  namespace: platform
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/custom-http-errors: "599" 
    cert-manager.io/cluster-issuer: letsencrypt-prod # If using SSL
spec:
  tls:
  - hosts:
    - s3.churchlify.com
    secretName: minio-api-tls
  rules:
  - host: s3.churchlify.com 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9000 # The API Port